tabWidth: 2
useTabs: false
endOfLine: lf
printWidth: 120
singleQuote: true
trailingComma: all
semi: true
arrowParens: avoid
plugins:
  - prettier-plugin-tailwindcss
tailwindConfig: tailwind.config.ts
