import { minify, Options as MinifyOptions } from 'html-minifier';
import UnoCSS from 'unocss/vite';
import { PluginOption, defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';

export default defineConfig({
  plugins: [
    UnoCSS(),
    minifyHtml({
      includeAutoGeneratedTags: true,
      removeAttributeQuotes: true,
      removeComments: true,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: false,
      removeStyleLinkTypeAttributes: true,
      removeEmptyAttributes: true,
      removeOptionalTags: true,
      preserveLineBreaks: false,
      sortClassName: true,
      useShortDoctype: true,
      collapseWhitespace: true,
      minifyJS: true,
    }),
  ],
});

function minifyHtml(options: MinifyOptions): PluginOption {
  return {
    name: 'config:minifyHtml',
    transformIndexHtml: {
      handler: html => minify(html, options),
    },
  };
}
