export type FLAG_NAME = keyof typeof FLAG_ICONS;

export const DEFAULT_ICON = '976070435240280116.png';

export const FLAG_ICONS = {
  STAFF: 'discordstaff.svg',
  PARTNER: 'discordpartner.svg',
  HYPESQUAD: 'hypesquadevents.svg',
  BUG_HUNTER_LEVEL_1: 'discordbughunter1.svg',
  MFA_SMS: '',
  PREMIUM_PROMO_DISMISSED: '',
  HYPESQUAD_ONLINE_HOUSE_1: 'hypesquadbravery.svg',
  HYPESQUAD_ONLINE_HOUSE_2: 'hypesquadbrilliance.svg',
  HYPESQUAD_ONLINE_HOUSE_3: 'hypesquadbalance.svg',
  PREMIUM_EARLY_SUPPORTER: 'discordearlysupporter.svg',
  TEAM_USER: '',
  INTERNAL_APPLICATION: '',
  SYSTEM: '',
  HAS_UNREAD_URGENT_MESSAGES: '',
  BUG_HUNTER_LEVEL_2: 'discordbughunter2',
  UNDERAGE_DELETED: '',
  VERIFIED_BOT: '',
  VERIFIED_DEVELOPER: 'discordbotdev.svg',
  CERTIFIED_MODERATOR: 'discordmod.svg',
  BOT_HTTP_INTERACTIONS: '',
  SPAMMER: '',
  DISABLE_PREMIUM: '',
  ACTIVE_DEVELOPER: 'activedeveloper.svg',
  HIGH_GLOBAL_RATE_LIMIT: '',
  DELETED: '',
  DISABLED_SUSPICIOUS_ACTIVITY: '',
  SELF_DELETED: '',
  PREMIUM_DISCRIMINATOR: '',
  USED_DESKTOP_CLIENT: '',
  USED_WEB_CLIENT: '',
  USED_MOBILE_CLIENT: '',
  DISABLED: '',
  VERIFIED_EMAIL: '',
  QUARANTINED: '',
  COLLABORATOR: '',
  RESTRICTED_COLLABORATOR: '',
};

// https://github.com/Delitefully/DiscordLists/blob/master/flags.md
export const FLAGS: [number, FLAG_NAME][] = [
  [1, 'STAFF'],
  [2, 'PARTNER'],
  [4, 'HYPESQUAD'],
  [8, 'BUG_HUNTER_LEVEL_1'],
  [16, 'MFA_SMS'],
  [32, 'PREMIUM_PROMO_DISMISSED'],
  [64, 'HYPESQUAD_ONLINE_HOUSE_1'],
  [128, 'HYPESQUAD_ONLINE_HOUSE_2'],
  [256, 'HYPESQUAD_ONLINE_HOUSE_3'],
  [512, 'PREMIUM_EARLY_SUPPORTER'],
  [1024, 'TEAM_USER'],
  [2048, 'INTERNAL_APPLICATION'],
  [4096, 'SYSTEM'],
  [8192, 'HAS_UNREAD_URGENT_MESSAGES'],
  [16384, 'BUG_HUNTER_LEVEL_2'],
  [32768, 'UNDERAGE_DELETED'],
  [65536, 'VERIFIED_BOT'],
  [131072, 'VERIFIED_DEVELOPER'],
  [262144, 'CERTIFIED_MODERATOR'],
  [524288, 'BOT_HTTP_INTERACTIONS'],
  [1048576, 'SPAMMER'],
  [2097152, 'DISABLE_PREMIUM'],
  [4194304, 'ACTIVE_DEVELOPER'],
  [8589934592, 'HIGH_GLOBAL_RATE_LIMIT'],
  [17179869184, 'DELETED'],
  [34359738368, 'DISABLED_SUSPICIOUS_ACTIVITY'],
  [68719476736, 'SELF_DELETED'],
  [137438953472, 'PREMIUM_DISCRIMINATOR'],
  [274877906944, 'USED_DESKTOP_CLIENT'],
  [549755813888, 'USED_WEB_CLIENT'],
  [1099511627776, 'USED_MOBILE_CLIENT'],
  [2199023255552, 'DISABLED'],
  [8796093022208, 'VERIFIED_EMAIL'],
  [17592186044416, 'QUARANTINED'],
  [1125899906842624, 'COLLABORATOR'],
  [2251799813685248, 'RESTRICTED_COLLABORATOR'],
];

// https://github.com/Delitefully/DiscordLists/blob/master/flags.md
// [ name, description, public, documented, 1 << shift ]
// prettier-ignore
export const FLAG_INFO: {[key in FLAG_NAME]: [string, string, boolean, boolean, number]} = {
  STAFF                        : [ 'Staff'                        ,'Discord Employee'                                            ,true  ,true  ,0  ],
  PARTNER                      : [ 'Partner'                      ,'Discord Partner'                                             ,true  ,true  ,1  ],
  HYPESQUAD                    : [ 'Hypesquad'                    ,'HypeSquad Events'                                            ,true  ,true  ,2  ],
  BUG_HUNTER_LEVEL_1           : [ 'Bug Hunter Level 1'           ,'Bug Hunter Level 1'                                          ,true  ,true  ,3  ],
  MFA_SMS                      : [ 'Mfa Sms'                      ,'SMS recovery for 2FA enabled'                                ,false ,false ,4  ],
  PREMIUM_PROMO_DISMISSED      : [ 'Premium Promo Dismissed'      ,'Dismissed Nitro promotion'                                   ,false ,false ,5  ],
  HYPESQUAD_ONLINE_HOUSE_1     : [ 'HypeSquad Bravery'            ,'HypeSquad Online House Bravery'                              ,true  ,true  ,6  ],
  HYPESQUAD_ONLINE_HOUSE_2     : [ 'HypeSquad Brilliance'         ,'HypeSquad Online House Brilliance'                           ,true  ,true  ,7  ],
  HYPESQUAD_ONLINE_HOUSE_3     : [ 'HypeSquad Balance'            ,'HypeSquad Online House Balance'                              ,true  ,true  ,8  ],
  PREMIUM_EARLY_SUPPORTER      : [ 'Early Supporter'              ,'Early Supporter'                                             ,true  ,true  ,9  ],
  TEAM_USER                    : [ 'Team User'                    ,'Team User'                                                   ,true  ,true  ,10 ],
  INTERNAL_APPLICATION         : [ 'Internal Application'         ,'Relates to partner/verification applications.'               ,false ,false ,11 ],
  SYSTEM                       : [ 'System'                       ,'System User'                                                 ,true  ,true  ,12 ],
  HAS_UNREAD_URGENT_MESSAGES   : [ 'Has Unread Urgent Messages'   ,'Has an unread system message'                                ,false ,false ,13 ],
  BUG_HUNTER_LEVEL_2           : [ 'Bug Hunter Level 2'           ,'Bug Hunter Level 2'                                          ,true  ,true  ,14 ],
  UNDERAGE_DELETED             : [ 'Underage Deleted'             ,'Pending deletion for being underage in DOB prompt'           ,false ,false ,15 ],
  VERIFIED_BOT                 : [ 'Verified Bot'                 ,'Verified Bot'                                                ,true  ,true  ,16 ],
  VERIFIED_DEVELOPER           : [ 'Early Verified Bot Developer' ,'Early Verified Bot Developer'                                ,true  ,true  ,17 ],
  CERTIFIED_MODERATOR          : [ 'Certified Moderator'          ,'Moderator Programs Alumni'                                   ,true  ,true  ,18 ],
  BOT_HTTP_INTERACTIONS        : [ 'Bot Http Interactions'        ,'Bot has set an interactions endpoint url'                    ,true  ,true  ,19 ],
  SPAMMER                      : [ 'Spammer'                      ,'User is disabled for being a spammer'                        ,true  ,false ,20 ],
  DISABLE_PREMIUM              : [ 'Disable Premium'              ,'Disables Nitro Features'                                     ,false ,false ,21 ],
  ACTIVE_DEVELOPER             : [ 'Active Developer'             ,'User is an active developer'                                 ,true  ,true  ,22 ],
  HIGH_GLOBAL_RATE_LIMIT       : [ 'High Global Rate Limit'       ,'Account has a high global ratelimit'                         ,false ,false ,33 ],
  DELETED                      : [ 'Deleted'                      ,'Account has been deleted'                                    ,false ,false ,34 ],
  DISABLED_SUSPICIOUS_ACTIVITY : [ 'Disabled Suspicious Activity' ,'Account has been disabled for suspicious activity'           ,false ,false ,35 ],
  SELF_DELETED                 : [ 'Self Deleted'                 ,'Account was deleted by the user'                             ,false ,false ,36 ],
  PREMIUM_DISCRIMINATOR        : [ 'Premium Discriminator'        ,'User has a premium discriminator'                            ,true  ,false ,37 ],
  USED_DESKTOP_CLIENT          : [ 'Used Desktop Client'          ,'User has used the desktop client'                            ,true  ,false ,38 ],
  USED_WEB_CLIENT              : [ 'Used Web Client'              ,'User has used the web client'                                ,true  ,false ,39 ],
  USED_MOBILE_CLIENT           : [ 'Used Mobile Client'           ,'User has used the mobile client'                             ,true  ,false ,40 ],
  DISABLED                     : [ 'Disabled'                     ,'User is currently temporarily or permanently disabled'       ,false ,false ,41 ],
  VERIFIED_EMAIL               : [ 'Verified Email'               ,'User has a verified email'                                   ,true  ,false ,43 ],
  QUARANTINED                  : [ 'Quarantined'                  ,'User account is quarantined'                                 ,false ,false ,44 ],
  COLLABORATOR                 : [ 'Collaborator'                 ,'User is a collaborator and has staff permissions'            ,true  ,false ,50 ],
  RESTRICTED_COLLABORATOR      : [ 'Restricted Collaborator'      ,'User is a restricted collaborator and has staff permissions' ,true  ,false ,51 ],
}
